# Generated by Django 2.2.4 on 2019-08-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'BIN ID ',
                'verbose_name_plural': 'BIN ID',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('garbage_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longtitude', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'LOCATION',
                'verbose_name_plural': 'LOCATION',
            },
        ),
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('maid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('maid_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'MODELNAME',
                'verbose_name_plural': 'MODELNAMEs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('notification_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('responsible_id', models.IntegerField(primary_key=True, serialize=False)),
                ('maid_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Maid')),
            ],
            options={
                'verbose_name': 'MODELNAME',
                'verbose_name_plural': 'MODELNAMEs',
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('send_id', models.IntegerField(primary_key=True, serialize=False)),
                ('notification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Message')),
                ('responsible_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Responsible')),
            ],
            options={
                'verbose_name': 'Send',
                'verbose_name_plural': 'Send',
            },
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Maid')),
            ],
            options={
                'verbose_name': 'MODELNAME',
                'verbose_name_plural': 'MODELNAMEs',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Bin')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.RegisteredUser')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Locate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('locate_date', models.DateTimeField(auto_now=True)),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Bin')),
            ],
            options={
                'verbose_name': 'LOCATE',
                'verbose_name_plural': 'LOCATE',
            },
        ),
        migrations.CreateModel(
            name='GarbageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_name', models.CharField(max_length=200)),
                ('garbage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Location')),
            ],
            options={
                'verbose_name': 'GarbageType',
                'verbose_name_plural': 'GarbageType',
            },
        ),
    ]
