# Generated by Django 2.2.4 on 2019-08-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'verbose_name': 'Bin ID ', 'verbose_name_plural': 'Bin ID'},
        ),
        migrations.AlterModelOptions(
            name='locate',
            options={'verbose_name': 'Locate', 'verbose_name_plural': 'Locate'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='maid',
            options={'verbose_name': 'MaidName', 'verbose_name_plural': 'MaidNames'},
        ),
        migrations.AlterModelOptions(
            name='registereduser',
            options={'verbose_name': 'RegisteredUser', 'verbose_name_plural': 'RegisteredUsers'},
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'verbose_name': 'Responsible', 'verbose_name_plural': 'Responsibles'},
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Bin')),
                ('garbage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.GarbageType')),
            ],
        ),
    ]
