# Generated by Django 2.2.4 on 2019-08-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20190829_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contain',
        ),
    ]
