# Generated by Django 2.2.4 on 2019-09-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Bin ID ',
                'verbose_name_plural': 'Bin ID',
            },
        ),
        migrations.CreateModel(
            name='GarbageType',
            fields=[
                ('garbage_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('garbage_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'GarbageType',
                'verbose_name_plural': 'GarbageType',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longtitude', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('maid_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('maid_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Maid',
                'verbose_name_plural': 'Maids',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('notification_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('date_time_value', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'RegisteredUser',
                'verbose_name_plural': 'RegisteredUsers',
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('responsible_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Bin')),
                ('maid_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Maid')),
            ],
            options={
                'verbose_name': 'Responsible',
                'verbose_name_plural': 'Responsibles',
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('send_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('notification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Message')),
                ('responsible_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Responsible')),
            ],
            options={
                'verbose_name': 'Send',
                'verbose_name_plural': 'Send',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Bin')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.RegisteredUser')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Locate',
            fields=[
                ('locate_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Bin')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Location')),
            ],
            options={
                'verbose_name': 'Locate',
                'verbose_name_plural': 'Locate',
            },
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('contain_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('date_time_value', models.DateTimeField(auto_now=True)),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Bin')),
                ('garbage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.GarbageType')),
            ],
            options={
                'verbose_name': 'Contain',
                'verbose_name_plural': 'Contains',
            },
        ),
    ]
