# Generated by Django 2.2.4 on 2019-09-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contain',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='level',
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField()),
                ('date_time_value', models.DateTimeField(auto_now=True)),
                ('garbage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.GarbageType')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
    ]
